{{- if .Values.curator.config -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "curator.fullname" . }}-config
  labels:
    {{- include "curator.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "30"
data:
  {{- range $key, $value := .Values.curator.config }}
  {{- if $value }}
  {{ $key }}.php: {{ $value | toYaml | nindent 4 }}
  {{- end }}
  {{- end }}
{{ end }}