apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.mariadbOperator.database.name | default .Values.environment }}-mariadb # TODO allow this to be customized
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "30"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: k8s
  target:
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: {{ .Release.Name }}-database
      property: username
  - secretKey: password
    remoteRef:
      key: {{ .Release.Name }}-database
      property: password