{{ if (and .Values.persistence.enabled (not .Values.persistence.s3.enabled)) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  {{- with .Values.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.persistence.labels }}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ printf "%s-%s" "data" .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  {{- with .Values.persistence.accessModes }}
  accessModes:
  {{- toYaml . | nindent 2 }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
{{- end -}}