# .github/workflows/chart-release.yml
name: Release Helm Chart

on:
  release:
    types: [published]

jobs:
  chart:
    runs-on: us-east-2-development
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          charts_dir: charts
