name: Release Helm Chart

on:
  release:
    types: [published, created, released]
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to package'
        required: false
        default: 'latest'

jobs:
  chart:
    runs-on: us-east-2-development
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Debug release event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Release action: ${{ github.event.action }}"
          echo "Release tag: ${{ github.event.release.tag_name }}"
          echo "Release published: ${{ github.event.release.published_at }}"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          charts_dir: charts