name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      issues: write
      pull-requests: write
    runs-on: us-east-2-development-docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'
      
      - name: Setup yq
        uses: mikefarah/yq@master

      - name: Install dependencies
        run: npm install

      - name: Debug yq and Chart.yaml before release
        run: |
          echo "=== YQ Version ==="
          yq --version
          echo "=== Chart.yaml before ==="
          cat charts/curator/Chart.yaml
          echo "=== Test yq command ==="
          yq eval '.version' charts/curator/Chart.yaml

      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: semantic-release:*
        run: npx semantic-release

      - name: Debug Chart.yaml after release
        run: |
          echo "=== Chart.yaml after ==="
          cat charts/curator/Chart.yaml
